// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/deepinfra.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const DEEPINFRA_MODELS: ChatModelCatalog<typeof values, "deepinfra"> =
	flattenChatModelCatalog("deepinfra", values);

export const DEEPINFRA_IMAGE_MODELS: ImageModelCatalog<typeof values, "deepinfra"> =
	flattenImageModelCatalog("deepinfra", values);

export const DEEPINFRA_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "deepinfra"> =
	flattenClassifierModelCatalog("deepinfra", values);
