// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const META_MODELS = {
	"muse-spark-1.1": {
		id: "muse-spark-1.1",
		name: "Muse Spark 1.1",
		api: "openai-responses",
		provider: "meta",
		baseUrl: "https://api.meta.ai/v1",
		thinkingLevelMap: {"off":null},
		compat: {"replayReasoning":false},
		reasoning: true,
		input: ["text", "image"],
		cost: {
			input: 1.25,
			output: 4.25,
			cacheRead: 0.125,
			cacheWrite: 0,
		},
		contextWindow: 1048576,
		maxTokens: 131072,
	} satisfies Model<"openai-responses">,
} as const;
